# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absent',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('not_defined', 'Unentschuldigt'), ('match', 'Spiel'), ('other', 'Sonstige'), ('sick', 'Krank'), ('work', 'Beruf'), ('education', 'Schule / Ausbildung'), ('injured', 'Verletzt')], max_length=70),
        ),
    ]
