# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0002_auto_20180316_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='coordination1',
        ),
        migrations.RemoveField(
            model_name='session',
            name='coordination2',
        ),
        migrations.AddField(
            model_name='session',
            name='coordination',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('orientation', 'Orientierung'), ('rhytm', 'Rhytmus'), ('balance', 'Gleichgewicht'), ('differentiation', 'Differenzierung'), ('reaction', 'Reaktion')], max_length=70),
        ),
        migrations.AlterField(
            model_name='keeper',
            name='club',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
